### ISSUE TITLE
Version without crashlytics (or Google Analytics) for F-Droid

### ISSUE THREAD

**Issue by pserwylo** [mapsquare/osm-contributor#1]
I'd love to build this app for distribution with [F-Droid](https://f-droid.org/), but it depends on the non-free Crashlytics and Google Analytics. Before building, it is relatively straightforward to replace Google Analytics with NoAnalytics, but crashlytics is more difficult. Would you be able to add a gradle build flavour which when invoked, excludes crashlytics and Google Analytics?

**Comment by loicortola** [comment]
Hi Peter,
thanks for the issue!
fredszaq is working on it, flavour should be available within the hour.
The tricky thing was that crashlytics is also part of the buildscript...
I see that you're contributing on Android projects. 
Would you like to be a part of the project development team?

**Comment by pserwylo** [comment]
@loicortola, thanks for the fix, that's great and provides a nice FOSS build with only FOSS dependencies. I must admit though that I've made a mistake. I was going through the list of apps people have asked to be added to F-Droid, and I didn't realise the mechanism behind osm-contributor - users requesting certain regions of interest and get apps specifically built for them and their mapping parties. It's a really cool approach, but unfortunately I don't think it is suitable for F-Droid, which really only distributes traditional .apks (i.e. each user has the same .apk which was built once by F-Droid). Please let me know if I've gotten this wrong, and there is indeed one .apk that can be used for all users.

As for contributing to this app, I'll keep an eye on your progress because I think it is cool and I also love the OSM project in general. But I have a huge amount of other commitments right now. All the best with this project.

**Comment by fredszaq** [comment]
@pserwylo the store falvor of the app is destined to be published on app stores and should be suitable for f-droid (same apk for all users). We're still working on it through, expect an usable version within the next few weeks

**Comment by loicortola** [comment]
@pserwylo, exactly as @fredszaq said. One flavour is for mapping parties (all custom), but there is a general-purpose app already available on the store. This is the one flavoured for f-droid.

**Comment by mvdan** [comment]
@loicortola @fredszaq I just had a look at 2.2.2, thanks for your help on a foss build!

It still doesn't build out of the box, though. It requires the builder to sign up for a bing maps api key. We can't work with that - we have thousands of apps.

I see two possible solutions:

* Publish the api key (even if hidden as a hex/base64 string)
* Provide a way to build without a bing maps api key
